version: "3.7"

services:
 #Rails SampleApplication
 app:
   build: .
   stdin_open: true
   tty: true
  #remove process normally
   init: true

   ports:
    - "3000:3000"

   volumes:
<<<<<<< HEAD
   #  - .:/app

    #Take Node_modules from images
     - /app/node_modules
=======
    - .:/app
    #Use node_modules from images
    - /app/node_modules
>>>>>>> modify_docker
