version: "3.7"

services:
 #Rails SampleApplication
 app:
   build: .

  #remove process normally
   init: true

   ports:
    - "3000:3000"

   volumes:
   #  - .:/app

    #Take Node_modules from images
     - /app/node_modules
